- name: Installing...nginx
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: install mysql
    ansible.builtin.package:
     name: mysql
     state: present
  

  
  - name: printing ngix is done
    ansible.builtin.debug:
      msg: "installing ngix and mysql is succesfull...thanks"
